DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NzU4MzExMjUsInVzZXJJRCI6MX0.OzDVyOxtx2BJ2ruX0hzkyKxhUTEiLc8H8N6RXKLAHl8