POST http://localhost:8080/events
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RfbWVAZXhhbXBsZS5jb20iLCJleHAiOjE3NzU2OTI0ODIsInVzZXJJRCI6Mn0.WstdP6S1xdg05ffoI01Psr2S-zqs87CxecQ9FTIV77U

{
    "name": "Test Event 3",
    "description": "Another test Event",
    "location": "Different Test Location",
    "dateTime": "2024-10-15T14:00:00Z"
}