DELETE http://localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzc1NzU2MTU4LCJ1c2VySUQiOjJ9.TThW4Ov4D7QIqqlAFGO5VIr-P1AhnqfxKi4Rt4GwmFQ
  
     